services:
  - type: web
    name: mit-nova
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: streamlit run MIT_Nova_1.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
