services:
  - type: web
    name: mit-nova
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run MIT_Nova_1.py --server.address=0.0.0.0 --server.port=$PORT
    autoDeploy: true
